# Generated by Django 5.0.2 on 2024-07-16 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=30)),
                ('ultimo_nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=30)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Novo', 'Novo'), ('Perdido', 'Perdido'), ('Contatado', 'Contatado'), ('Qualificado', 'Qualificado')], default='Novo', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('Chamada', 'Chamada'), ('Email', 'Email'), ('Reunião', 'Reunião'), ('Outro', 'Outro')], max_length=10)),
                ('resumo', models.TextField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estagio', models.CharField(choices=[('Prospecção', 'Prospecção'), ('Proposta', 'Proposta'), ('Negociação', 'Negociação'), ('Fechado', 'Fechado')], default='Prospecção', max_length=20)),
                ('data_fechamento_prevista', models.DateField()),
                ('data_fechamento_real', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('leads_atribuídos', models.ManyToManyField(blank=True, to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('data_vencimento', models.DateField()),
                ('concluida', models.BooleanField(default=False)),
                ('lead_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lead')),
                ('atribuida_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.vendedor')),
            ],
        ),
    ]
